////
////
//// This file is generated by the Pulse2Rust tool
////
////

pub fn extract_term(arr: &mut [u8], p: (), s: ()) -> u32 {
    let b0 = super::pulse_lib_array_ptsto::op_Array_Access(arr, 4, (), ());
    let b1 = super::pulse_lib_array_ptsto::op_Array_Access(arr, 5, (), ());
    let b2 = super::pulse_lib_array_ptsto::op_Array_Access(arr, 6, (), ());
    let b3 = super::pulse_lib_array_ptsto::op_Array_Access(arr, 7, (), ());
    let v_nat = super::fstar_uint8::v(b0) * 16777216 + super::fstar_uint8::v(b1) * 65536
        + super::fstar_uint8::v(b2) * 256 + super::fstar_uint8::v(b3);
    super::fstar_uint32::uint_to_t(v_nat)
}
#[derive(Debug, Clone, PartialEq)]
pub enum raft_state {
    Follower,
    Candidate,
    Leader,
}
#[derive(Debug)]
pub struct server_state {
    pub current_term: u32,
    pub state: super::server::raft_state,
    pub voted_for: std::option::Option<u32>,
    pub commit_index: u32,
    pub previous_log_index: u32,
}
pub fn handle_heartbeat(
    s: &mut super::server::server_state,
    data: &mut [u8],
    p_s: (),
    p_data: (),
    st: (),
    s_seq: (),
    st1: (),
) -> () {
    let st2 = super::pulse_lib_reference::op_Bang(s, (), ());
    if st2.state == super::server::raft_state::Leader {
        let term = super::server::extract_term(data, (), ());
    } else {
        ()
    }
}

